apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx-proxy-container
        image: dothiengiang0001/nginx-proxy:latest
        ports:
        - containerPort: 80  # Chỉ định cổng container 80
