apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: static-web-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081  # NodePort value, adjust as needed
